version: '3.8'

services:
  # Backend (API)
  backend:
    image: ${DOCKER_USERNAME}/gv-marketing-backend:latest
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Supabase PostgreSQL
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - FRONTEND_URL=${FRONTEND_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Frontend (React)
  frontend:
    image: ${DOCKER_USERNAME}/gv-marketing-frontend:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Watchtower - Auto-update containers quando houver nova imagem
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
