version: '3.8'

services:
  # Backend (API)
  backend:
    image: ${DOCKER_USERNAME}/gv-marketing-backend:latest
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Supabase PostgreSQL (Connection Pooler)
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=9b1af44452364c0ef77cf19d7b0fb495868320c2f7f31bf98ed8a00c5a9dc08b6aef35e6db6ef407daed9025c4b948128dbe685f48d91679c6885ccdb5639bda
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://72.61.135.194:8080
      - ADMIN_EMAIL=admin@gvmarketing.com
      - ADMIN_PASSWORD=GVMarketing2024!@Secure
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Frontend (React)
  frontend:
    image: ${DOCKER_USERNAME}/gv-marketing-frontend:latest
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Watchtower - Auto-update containers quando houver nova imagem
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
